# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db48c7ea1e1db65a8870fa03da2cf82fa696674f10d3acaf0b71485412c4d059d6734afccca8e3e648a52eaecf30e38ea82209c9efe70a3a8582426caf67576

test:
  secret_key_base: 644fdcd4d21bec215fff7563deebe52a28a5f697e23d305caf9b8c551697bdbb4c100af60ef3df9d167840cefe9e32835264a1a6e6cfe794657cc9d9184c5453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
